apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    {{- include "findery-market.labels" . | nindent 4 }}
spec:
  type: {{ .Values.paymentService.service.type }}
  ports:
    - port: {{ .Values.paymentService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: payment-service
