apiVersion: v1
kind: Service
metadata:
  # name: {{ include "findery-market.fullname" . }}-user-service
  name: user-service
  labels:
    {{- include "findery-market.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: user-service
